version: '3'
services:
  db:
    hostname: db
    container_name: db
    image: postgres:13.6
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 5s
      retries: 10
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  server:
    container_name: server
    build:
      context: ./packages/server
      dockerfile: Dockerfile.server
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - HOST=${HOST}
      - SERVER_PORT=${SERVER_PORT}
    env_file:
      - .env
    ports:
      - '3001:3001'
    volumes:
      - ./packages/server:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${HOST}:${SERVER_PORT}/healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 10

  client:
    container_name: client
    build:
      context: ./packages/client
      dockerfile: Dockerfile.client
    depends_on:
      server:
        condition: service_healthy
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - VITE_CLIENT_PORT=${VITE_CLIENT_PORT}
    env_file:
      - .env
    ports:
      - '${VITE_CLIENT_PORT}:${VITE_CLIENT_PORT}'
    volumes:
      - .:/app
      - /app/node_modules
      - ./.env:/app/.env
