version: '3'
services:
  db:
    hostname: db
    container_name: db
    image: postgres:13.6
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    container_name: server
    build:
      context: ./packages/server
      dockerfile: Dockerfile.server
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./packages/server:/app
      - /app/node_modules
      - ./.env:/app/.env

  client:
    container_name: client
    build:
      context: ./packages/client 
      dockerfile: Dockerfile.client
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    env_file:
      - .env
    ports:
      - '5173:5173'
    volumes: 
      - ./packages/client:/app
      - /app/node_modules
      - ./.env:/app/.env
